# Generated by Django 2.1.1 on 2018-09-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugatricle',
            new_name='slug',
        ),
    ]
