# Generated by Django 2.1 on 2018-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('trackname', models.CharField(max_length=250)),
                ('Artist', models.CharField(max_length=250)),
                ('streams', models.BigIntegerField()),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=250)),
            ],
        ),
    ]
